import Footer from '@/components/home/footer';
import { Navbar } from '@/components/home/navbar';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: '--font-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className={cn('font-sans', plusJakartaSans.variable)}>
            <body
                suppressHydrationWarning
                className={`${plusJakartaSans.variable} antialiased  mx-auto `}>
                <div className='flex min-h-screen w-full flex-col bg-background selection:bg-primary/20 mx-auto'>
                    {/* The Navbar floats absolutely over the entire Hero */}
                    <Navbar />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}

